apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: app
  name: test-app
spec:
  replicas: 2
  selector:
    matchLabels:
      run: app
  template:
    metadata:
      labels:
        run: app
    spec:
      containers:
      - name: app
        image: vinayakpadukone/mypf
        ports:
        - containerPort: 3000
